    witter:
        build: .
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        working_dir: /usr/src/app 
        ports:
            - 8888:8888
            - 8889:8889